### PR TITLE
Made this work with rails 3.2

### PR DESCRIPTION
**Pull request by ncri**

### CODE REVIEW

**Comment by aka47** [comment]
+1 it is not usable with rails 3.2 .. which is the offical rails version .. please accept this pull request..

**Comment by mattgreen** [comment]
+1

Please accept.

**Comment by tiegz** [comment]
+1

**Comment by thorncp** [comment]
+1 Confirmed to work with 3.2

**Comment by dynamix** [comment]
+1

**Comment by aledalgrande** [comment]
It doesn't seem this project is maintained any more.

**Comment by ncri** [comment]
Nope. I'm wondering if possibly validation reflection is already in Rails version > 3 or > 3.1? Just a guess. Haven't looked into it.

**Comment by tiegz** [comment]
Yeah, I'm not sure if the whole plugin is in there, but in at least 3.2 you can do stuff like `User.reflections[:comments]`

**Comment by tiegz** [comment]
(just verified that this is in 3.0 too)

**Comment by americos** [comment]
+1
Just tested with Rails 3.2.13. Unless this project is not more maintain, please accept pull request

**Comment by RedaBenh** [comment]
+1 i install it and i have the same issue

**Pull request merged**
